site_name: "test documentation repo"
site_description: "this is a test"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/mlg-test-repo-21"
edit_uri: edit/main/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
